"""Grade the vendored example repositories with the real engine.

Shared by `test_fixture_corpus.py` and
`scripts/refresh-fixture-expectations.py`, so the corpus is checked and
regenerated by exactly the same code path.

Every fixture is graded in a subprocess: `pytest_runner.run()` starts nested
pytest sessions, and running those inside the session that checks them would
share the module cache and the assertion-rewrite state between fixtures.
"""

import json
import os
import pathlib
import re
import shutil
import subprocess
import sys

FIXTURES = pathlib.Path(__file__).resolve().parent / 'fixtures'
SRC = pathlib.Path(__file__).resolve().parents[1] / 'src'
EXPECTATION_FILENAME = 'expected.json'
CASE_POINTS = 2
CASE_TIMEOUT = 10

DRIVER = '''\
"""Grade the copied fixture and dump the section result."""
import json
import sys

from pygrader50 import pytest_runner
from pygrader50.config import Testcase

names = json.loads(sys.argv[2])
cases = [Testcase(name=name, function=name, timeout={timeout}, points={points})
         for name in names]
with open(sys.argv[1], 'w', encoding='UTF-8') as handle:
    json.dump(pytest_runner.run(cases), handle)
'''


def fixtures() -> list[pathlib.Path]:
    """Every vendored example repository, in a stable order."""
    return sorted(path for path in FIXTURES.iterdir() if path.is_dir())


def case_names(fixture: pathlib.Path) -> list[str]:
    """The test functions declared in the fixture, deduplicated and sorted.

    A name that two classes both declare is one case for us: `-k` selects both
    and the first failure decides, which is what a `unittests.json` entry
    naming that function would do in a real assignment too.
    """
    names: set[str] = set()
    for test_file in sorted(fixture.glob('*_test.py')):
        names.update(re.findall(r'def (test_\w+)', test_file.read_text(encoding='UTF-8')))
    return sorted(names)


def grade(fixture: pathlib.Path, workdir: pathlib.Path) -> list[dict]:
    """Copy the fixture to `workdir`, grade it, and return the feedback rows."""
    checkout = workdir / fixture.name
    shutil.copytree(fixture, checkout)
    (checkout / EXPECTATION_FILENAME).unlink(missing_ok=True)

    names = case_names(fixture)
    driver = checkout / 'grade_fixture.py'
    driver.write_text(DRIVER.format(timeout=CASE_TIMEOUT, points=CASE_POINTS), encoding='UTF-8')
    output = checkout / 'section.json'

    completed = subprocess.run(
        [sys.executable, str(driver), str(output), json.dumps(names)],
        cwd=checkout, env=dict(os.environ, PYTHONPATH=str(SRC)),
        capture_output=True, text=True, check=False,
    )
    if not output.is_file():
        raise RuntimeError(f'{fixture.name}: the grader wrote nothing\n{completed.stderr}')
    return json.loads(output.read_text(encoding='UTF-8'))['feedback']


def expectation(fixture: pathlib.Path) -> dict:
    """The recorded expectation for a fixture."""
    path = fixture / EXPECTATION_FILENAME
    return json.loads(path.read_text(encoding='UTF-8'))


def mismatches(expected: dict, actual: list[dict]) -> list[str]:
    """Human-readable differences between a recorded and a fresh grading.

    `match: "contains"` marks a fixture whose feedback quotes CPython itself.
    The wording of a SyntaxError or an ImportError can differ between the Python
    versions the CI matrix covers, so those expectations list the substrings
    that carry the meaning instead of the whole sentence — and are maintained by
    hand, not regenerated.
    """
    problems = []
    rows = expected['cases']
    if len(rows) != len(actual):
        return [f'{len(rows)} cases recorded, {len(actual)} graded']

    loose = expected.get('match') == 'contains'
    for want, got in zip(rows, actual):
        for field in ('name', 'points', 'expected', 'actual'):
            if want[field] != got[field]:
                problems.append(f'{want["name"]}.{field}: {got[field]!r} != {want[field]!r}')
        if loose:
            for fragment in want['feedback']:
                if fragment not in got['feedback']:
                    problems.append(
                        f'{want["name"]}.feedback: {got["feedback"]!r} misses {fragment!r}'
                    )
        elif want['feedback'] != got['feedback']:
            problems.append(
                f'{want["name"]}.feedback: {got["feedback"]!r} != {want["feedback"]!r}'
            )
    return problems
